version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands: 
            - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
            - apt-get update
            - apt-get install -y google-chrome-stable xvfb
            - npm i -g @angular/cli
            - npm i
    pre_build:
        commands: 
            - echo "run tests"
            - npm test
    build:
        commands:
            - echo "build"
            - ng build --prod

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: dist/lestes-tech