version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands: 
            - npm i -g @angular/cli
            - npm i
            - CHROME_BIN="node_modules/puppeteer/.local_chromium"
    pre_build:
        commands: 
            - echo "run tests"
            - npm test
    build:
        commands:
            - echo "build"
            - ng build --prod

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: dist/lestes-tech