version: 0.3

phases:
    install:
        runtime-versions:
            nodejs: 24
        commands: 
            - npm i -g @angular/cli
            - npm i
    pre_build:
        commands: 
            - echo "run tests"
            - npm test
    build:
        commands:
            - echo "build"
            - ng build --prod

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: dist/lestes-tech